"""Generate a new project (``pyssg new <name>``) and posts (``pyssg new post``).

``new_site`` resolves a theme, vendors its ``layouts``/``assets``/``content``
into a fresh directory, and writes a ``pyssg.config.py`` derived from the
theme's ``[config]`` preset. ``new_post`` drops a new Markdown stub with
frontmatter into the project's content directory.
"""

from __future__ import annotations

import datetime
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path

from pyssg.config import DEFAULT_CONFIG_FILENAME
from pyssg_cli.scaffold.themes import (
    ThemeManifest,
    load_manifest,
    resolve_theme,
)
from pyssg_plugins.permalink import slugify

_POST_TEMPLATE = """---
title: "{title}"
date: {date}
draft: false
tags: []
summary: ""
---

Write your post here.
"""


class ScaffoldError(Exception):
    """A site or post could not be scaffolded."""


@dataclass(slots=True)
class ScaffoldResult:
    path: Path
    manifest: ThemeManifest


def new_site(name: str, *, theme: str = "docs", sample: bool = True) -> ScaffoldResult:
    """Scaffold a new site directory from a theme."""

    target = Path(name)
    if target.exists() and any(target.iterdir()):
        raise ScaffoldError(
            f"Target directory '{name}' already exists and is not empty"
        )

    with tempfile.TemporaryDirectory(prefix="pyssg-theme-") as tmp:
        theme_dir = resolve_theme(theme, workdir=Path(tmp))
        manifest = load_manifest(theme_dir)

        target.mkdir(parents=True, exist_ok=True)
        _vendor(theme_dir, target, manifest, sample=sample)

        config_text = render_config(manifest, site_title=_titleize(target.name))
        (target / DEFAULT_CONFIG_FILENAME).write_text(config_text, encoding="utf-8")

    return ScaffoldResult(path=target, manifest=manifest)


def new_post(
    title: str,
    *,
    content_dir: Path | None = None,
    section: str | None = None,
    date: str | None = None,
) -> Path:
    """Create a new Markdown post stub under the content directory."""

    base = Path("content") if content_dir is None else Path(content_dir)
    if not base.is_dir():
        raise ScaffoldError(
            f"Content directory '{base}' not found. "
            f"Run 'pyssg new post' from a pyssg project root."
        )

    # Blog themes keep posts under content/blog; honour that by default so the
    # post is picked up by the blog listing without extra flags.
    if section is None and (base / "blog").is_dir():
        section = "blog"

    folder = base if not section else base / section
    folder.mkdir(parents=True, exist_ok=True)

    slug = slugify(title) or "post"
    path = folder / f"{slug}.md"
    if path.exists():
        raise ScaffoldError(f"Post already exists: {path}")

    body = _POST_TEMPLATE.format(
        title=title.replace('"', "'"),
        date=date or datetime.date.today().isoformat(),
    )
    path.write_text(body, encoding="utf-8")
    return path


def render_config(manifest: ThemeManifest, *, site_title: str) -> str:
    """Render the text of a ``pyssg.config.py`` from a theme manifest."""

    config = manifest.config
    preset = config.preset
    uses_assets = "assets" in manifest.include

    lines: list[str] = [
        '"""Site configuration generated by `pyssg new`."""',
        "",
        "from pathlib import Path",
        "",
        "from pyssg.config import Config",
    ]
    if uses_assets:
        lines.append("from pyssg_plugins import StaticFiles")
    lines.append(f"from pyssg_cli.presets import {preset}")
    lines += ["", "", "def config() -> Config:"]

    kwargs = list(config.options.items())
    if kwargs:
        lines.append(f"    plugins = {preset}(")
        for key, value in kwargs:
            lines.append(f"        {key}={value!r},")
        lines.append("    )")
    else:
        lines.append(f"    plugins = {preset}()")

    if uses_assets:
        lines.append(
            '    plugins.append(StaticFiles(directory="assets", dest="assets"))'
        )

    lines += [
        "    return Config(",
        f"        src=Path({config.src!r}),",
        f"        out=Path({config.out!r}),",
        "        options={",
        f"            {'title'!r}: {site_title!r},",
        f"            {'tagline'!r}: {''!r},",
        f"            {'base_url'!r}: {''!r},",
        f"            {'repo_url'!r}: {''!r},",
        "        },",
        "        plugins=plugins,",
        "    )",
        "",
    ]
    return "\n".join(lines)


def _vendor(
    theme_dir: Path, target: Path, manifest: ThemeManifest, *, sample: bool
) -> None:
    for name in manifest.include:
        source = theme_dir / name
        dest = target / name
        if not sample and name in manifest.sample:
            # Skip sample content but still create the (empty) directory so the
            # build has a content root to read from.
            dest.mkdir(parents=True, exist_ok=True)
            continue
        if not source.exists():
            continue
        if source.is_dir():
            shutil.copytree(source, dest, dirs_exist_ok=True)
        else:
            shutil.copy2(source, dest)


def _titleize(name: str) -> str:
    cleaned = name.replace("-", " ").replace("_", " ").strip()
    return cleaned.title() if cleaned else name
