blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/magiskboy/pyssg/discussions
    about: Ask questions and discuss ideas before opening an issue.
